controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
change_locale:
    path: /change-locale/{locale}
    controller: App\Controller\LocaleController::changeLocale
    requirements:
        locale: es|en